{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "[Errno 2] No such file or directory: 'uilogin.ui'", "severity": "ERROR", "timestamp": "2024-09-22T09:41:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "[Errno 2] No such file or directory: 'login.ui'", "severity": "ERROR", "timestamp": "2024-09-22T09:43:54Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "[Errno 2] No such file or directory: 'login.ui'", "severity": "ERROR", "timestamp": "2024-09-22T09:44:13Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''123''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:26:40Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:26:53Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:26:53Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''11''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:26:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''11''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:26:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''11''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:26:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''123''' at line 1", "severity": "ERROR", "timestamp": "2024-09-27T12:28:03Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "obtener_usuario() takes 2 positional arguments but 3 were given", "severity": "ERROR", "timestamp": "2024-09-27T12:29:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "obtener_usuario() takes 2 positional arguments but 3 were given", "severity": "ERROR", "timestamp": "2024-09-27T12:30:54Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'QLabel' object has no attribute 'set'", "severity": "ERROR", "timestamp": "2024-09-28T20:06:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'QLabel' object has no attribute 'set'", "severity": "ERROR", "timestamp": "2024-09-28T20:06:49Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'QLabel' object has no attribute 'set'", "severity": "ERROR", "timestamp": "2024-09-28T20:07:33Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "execute() missing 1 required positional argument: 'operation'", "severity": "ERROR", "timestamp": "2024-09-28T21:08:54Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "execute() missing 1 required positional argument: 'operation'", "severity": "ERROR", "timestamp": "2024-09-28T21:10:20Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:13:34Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:03Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:03Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-09-28T21:14:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'desconectar'", "severity": "ERROR", "timestamp": "2024-09-28T21:15:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:23:57Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:24:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:24:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:26:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:28:46Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:28:46Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:30:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:36:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:36:45Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-09-28T21:36:45Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar usuario: Not enough parameters for the SQL statement", "severity": "ERROR", "timestamp": "2024-09-30T15:12:25Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar usuario: Not enough parameters for the SQL statement", "severity": "ERROR", "timestamp": "2024-09-30T15:14:16Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'AgregarUsuario' object has no attribute 'txtNombreUsuario'", "severity": "ERROR", "timestamp": "2024-09-30T15:16:34Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'QPushButton' object has no attribute 'connect'", "severity": "ERROR", "timestamp": "2024-09-30T15:57:19Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'nombre' in 'where clause'", "severity": "ERROR", "timestamp": "2024-09-30T16:41:33Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al eliminar usuario: 1054 (42S22): Unknown column 'nombre' in 'where clause'", "severity": "ERROR", "timestamp": "2024-09-30T16:41:33Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al eliminar usuario: 1054 (42S22): Unknown column 'nombre' in 'where clause'", "severity": "ERROR", "timestamp": "2024-09-30T16:41:33Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:54:27Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:54:27Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:54:27Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:55:31Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:55:31Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:55:31Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:55:31Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:55:31Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:55:31Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:55:31Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:58:46Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:58:46Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T14:58:46Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'conneccion'", "severity": "ERROR", "timestamp": "2024-10-02T15:03:35Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T15:03:35Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MySQLConnection' object has no attribute 'desconeccion'", "severity": "ERROR", "timestamp": "2024-10-02T15:03:35Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-10-02T15:08:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-10-02T15:09:00Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-10-02T15:09:00Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'NoneType' object is not subscriptable", "severity": "ERROR", "timestamp": "2024-10-02T15:10:41Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "obtener_usuario() missing 1 required positional argument: 'contrasena'", "severity": "ERROR", "timestamp": "2024-10-05T19:09:21Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:21Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:21Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:21Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: Could not process parameters: str(prueba), it must be of type list, tuple or dict", "severity": "ERROR", "timestamp": "2024-10-05T19:10:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "non-hexadecimal number found in fromhex() arg at position 0", "severity": "ERROR", "timestamp": "2024-10-05T19:11:58Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "non-hexadecimal number found in fromhex() arg at position 0", "severity": "ERROR", "timestamp": "2024-10-05T19:12:16Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "non-hexadecimal number found in fromhex() arg at position 0", "severity": "ERROR", "timestamp": "2024-10-05T19:12:16Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "non-hexadecimal number found in fromhex() arg at position 0", "severity": "ERROR", "timestamp": "2024-10-05T19:13:12Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'tablapelis'", "severity": "ERROR", "timestamp": "2024-10-06T18:52:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'tablapelis'", "severity": "ERROR", "timestamp": "2024-10-06T18:59:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'tablapelis'", "severity": "ERROR", "timestamp": "2024-10-06T19:03:49Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'AgregarPeliculas' object has no attribute 'ruta_imagen'", "severity": "ERROR", "timestamp": "2024-10-08T20:46:20Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "insertar_pelicula() missing 1 required positional argument: 'fecha_fin'", "severity": "ERROR", "timestamp": "2024-10-08T20:51:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'nombre' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-08T20:53:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar pel\u00edcula: 1054 (42S22): Unknown column 'nombre' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-08T20:53:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar pel\u00edcula: 1054 (42S22): Unknown column 'nombre' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-08T20:53:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1136 (21S01): Column count doesn't match value count at row 1", "severity": "ERROR", "timestamp": "2024-10-08T20:56:26Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar pel\u00edcula: 1136 (21S01): Column count doesn't match value count at row 1", "severity": "ERROR", "timestamp": "2024-10-08T20:56:26Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar pel\u00edcula: 1136 (21S01): Column count doesn't match value count at row 1", "severity": "ERROR", "timestamp": "2024-10-08T20:56:26Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'method' object is not iterable", "severity": "ERROR", "timestamp": "2024-10-11T16:44:09Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'IdPeliculas' in 'where clause'", "severity": "ERROR", "timestamp": "2024-10-11T16:46:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al eliminar pel\u00edcula: 1054 (42S22): Unknown column 'IdPeliculas' in 'where clause'", "severity": "ERROR", "timestamp": "2024-10-11T16:46:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al eliminar pel\u00edcula: 1054 (42S22): Unknown column 'IdPeliculas' in 'where clause'", "severity": "ERROR", "timestamp": "2024-10-11T16:46:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "local variable 'nueva_ruta_imagen' referenced before assignment", "severity": "ERROR", "timestamp": "2024-10-11T17:05:21Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'IdGenero' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-21T21:33:02Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al obtener el ID del g\u00e9nero: 1054 (42S22): Unknown column 'IdGenero' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-21T21:33:02Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al obtener el ID del g\u00e9nero: 1054 (42S22): Unknown column 'IdGenero' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-21T21:33:02Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 el g\u00e9nero  en la base de datos.", "severity": "ERROR", "timestamp": "2024-10-21T21:48:57Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 el g\u00e9nero  en la base de datos.", "severity": "ERROR", "timestamp": "2024-10-21T21:51:00Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'abrir_agregar_pelicula'", "severity": "ERROR", "timestamp": "2024-10-22T18:19:59Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'usuarios_actualizados'", "severity": "ERROR", "timestamp": "2024-10-22T18:21:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'usuarios_actualizados'", "severity": "ERROR", "timestamp": "2024-10-22T18:24:13Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'usuarios_actualizados'", "severity": "ERROR", "timestamp": "2024-10-22T18:24:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'ModificarPelicula' object has no attribute 'comboBox_peliculas'", "severity": "ERROR", "timestamp": "2024-10-22T20:02:02Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_datos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-22T20:03:49Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_datos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-22T20:04:04Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_datos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-22T20:04:04Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_datos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-22T20:06:47Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_datos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-22T20:09:01Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_datos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-22T20:11:51Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "arguments did not match any overloaded call:\n  fromString(string: Optional[str], format: Qt.DateFormat = Qt.TextDate): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str]): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str], cal: QCalendar): argument 1 has unexpected type 'datetime.date'", "severity": "ERROR", "timestamp": "2024-10-22T20:14:59Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "arguments did not match any overloaded call:\n  fromString(string: Optional[str], format: Qt.DateFormat = Qt.TextDate): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str]): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str], cal: QCalendar): argument 1 has unexpected type 'datetime.date'", "severity": "ERROR", "timestamp": "2024-10-23T10:34:05Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "arguments did not match any overloaded call:\n  fromString(string: Optional[str], format: Qt.DateFormat = Qt.TextDate): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str]): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str], cal: QCalendar): argument 1 has unexpected type 'datetime.date'", "severity": "ERROR", "timestamp": "2024-10-23T10:35:04Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "arguments did not match any overloaded call:\n  fromString(string: Optional[str], format: Qt.DateFormat = Qt.TextDate): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str]): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str], cal: QCalendar): argument 1 has unexpected type 'datetime.date'", "severity": "ERROR", "timestamp": "2024-10-23T10:35:04Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "arguments did not match any overloaded call:\n  fromString(string: Optional[str], format: Qt.DateFormat = Qt.TextDate): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str]): argument 1 has unexpected type 'datetime.date'\n  fromString(s: Optional[str], format: Optional[str], cal: QCalendar): argument 1 has unexpected type 'datetime.date'", "severity": "ERROR", "timestamp": "2024-10-23T10:41:09Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "isinstance() arg 2 must be a type or tuple of types", "severity": "ERROR", "timestamp": "2024-10-23T10:44:35Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "isinstance() arg 2 must be a type or tuple of types", "severity": "ERROR", "timestamp": "2024-10-23T10:56:16Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_generos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-23T11:01:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "type object 'datetime.datetime' has no attribute 'datetime'", "severity": "ERROR", "timestamp": "2024-10-23T11:05:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "type object 'datetime.datetime' has no attribute 'datetime'", "severity": "ERROR", "timestamp": "2024-10-23T11:06:11Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "type object 'datetime.datetime' has no attribute 'datetime'", "severity": "ERROR", "timestamp": "2024-10-23T11:07:36Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_generos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-23T11:10:21Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'ModificarPelicula' object has no attribute 'dateEdit_inicio'", "severity": "ERROR", "timestamp": "2024-10-23T11:11:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_generos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-23T11:16:09Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_generos_pelicula'", "severity": "ERROR", "timestamp": "2024-10-23T11:19:50Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 21", "severity": "ERROR", "timestamp": "2024-10-23T12:26:49Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 21", "severity": "ERROR", "timestamp": "2024-10-23T12:26:49Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 21", "severity": "ERROR", "timestamp": "2024-10-23T12:26:49Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 19", "severity": "ERROR", "timestamp": "2024-10-23T12:27:13Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 19", "severity": "ERROR", "timestamp": "2024-10-23T12:27:13Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 19", "severity": "ERROR", "timestamp": "2024-10-23T12:27:13Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 19", "severity": "ERROR", "timestamp": "2024-10-23T12:27:13Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 19", "severity": "ERROR", "timestamp": "2024-10-23T12:27:13Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 19", "severity": "ERROR", "timestamp": "2024-10-23T12:27:13Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 19", "severity": "ERROR", "timestamp": "2024-10-23T12:27:13Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 21", "severity": "ERROR", "timestamp": "2024-10-23T12:32:00Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 21", "severity": "ERROR", "timestamp": "2024-10-23T12:32:00Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 21", "severity": "ERROR", "timestamp": "2024-10-23T12:32:00Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 19", "severity": "ERROR", "timestamp": "2024-10-23T12:36:57Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 19", "severity": "ERROR", "timestamp": "2024-10-23T12:36:57Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 19", "severity": "ERROR", "timestamp": "2024-10-23T12:36:57Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 21", "severity": "ERROR", "timestamp": "2024-10-23T12:40:16Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 21", "severity": "ERROR", "timestamp": "2024-10-23T12:40:16Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 21", "severity": "ERROR", "timestamp": "2024-10-23T12:40:16Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 27, "message": "Intentando modificar pel\u00edcula con Id 19", "severity": "INFO", "timestamp": "2024-10-23T12:43:04Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 19", "severity": "ERROR", "timestamp": "2024-10-23T12:43:04Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 19", "severity": "ERROR", "timestamp": "2024-10-23T12:43:04Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 19", "severity": "ERROR", "timestamp": "2024-10-23T12:43:04Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 19", "severity": "ERROR", "timestamp": "2024-10-23T12:43:04Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 19", "severity": "ERROR", "timestamp": "2024-10-23T12:43:04Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 27, "message": "Intentando modificar pel\u00edcula con Id 22", "severity": "INFO", "timestamp": "2024-10-23T12:45:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 27, "message": "Intentando modificar pel\u00edcula con Id 22", "severity": "INFO", "timestamp": "2024-10-23T12:45:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 27, "message": "Intentando modificar pel\u00edcula con Id 22", "severity": "INFO", "timestamp": "2024-10-23T12:45:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 27, "message": "Intentando modificar pel\u00edcula con Id 22", "severity": "INFO", "timestamp": "2024-10-23T12:45:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:45:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:45:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:45:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:45:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:45:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:45:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:45:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:45:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:45:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:45:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:45:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 27, "message": "Intentando modificar pel\u00edcula con Id 22", "severity": "INFO", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 27, "message": "Intentando modificar pel\u00edcula con Id 22", "severity": "INFO", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 27, "message": "Intentando modificar pel\u00edcula con Id 22", "severity": "INFO", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 27, "message": "Intentando modificar pel\u00edcula con Id 22", "severity": "INFO", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 27, "message": "Intentando modificar pel\u00edcula con Id 22", "severity": "INFO", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 27, "message": "Intentando modificar pel\u00edcula con Id 22", "severity": "INFO", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 27, "message": "Intentando modificar pel\u00edcula con Id 22", "severity": "INFO", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:48:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:59:39Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:59:39Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:59:39Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:59:51Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:59:51Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:59:51Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:59:51Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:59:51Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:59:51Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T12:59:51Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T13:11:29Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T13:11:29Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 22", "severity": "ERROR", "timestamp": "2024-10-23T13:11:29Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 23", "severity": "ERROR", "timestamp": "2024-10-23T13:12:26Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 23", "severity": "ERROR", "timestamp": "2024-10-23T13:12:26Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 23", "severity": "ERROR", "timestamp": "2024-10-23T13:12:26Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 23", "severity": "ERROR", "timestamp": "2024-10-23T13:12:26Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 23", "severity": "ERROR", "timestamp": "2024-10-23T13:12:26Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 23", "severity": "ERROR", "timestamp": "2024-10-23T13:12:26Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 23", "severity": "ERROR", "timestamp": "2024-10-23T13:12:26Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 23", "severity": "ERROR", "timestamp": "2024-10-23T13:15:39Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 23", "severity": "ERROR", "timestamp": "2024-10-23T13:15:39Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 23", "severity": "ERROR", "timestamp": "2024-10-23T13:15:39Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'desconexion'", "severity": "ERROR", "timestamp": "2024-10-23T13:20:55Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'desconexion'", "severity": "ERROR", "timestamp": "2024-10-23T13:22:11Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'desconexion'", "severity": "ERROR", "timestamp": "2024-10-23T13:22:11Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'desconexion'", "severity": "ERROR", "timestamp": "2024-10-23T13:25:09Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "2055: Lost connection to MySQL server at '127.0.0.1:3306', system error: 10038 Se intent\u00f3 realizar una operaci\u00f3n en un elemento que no es un socket", "severity": "ERROR", "timestamp": "2024-10-23T13:26:40Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al eliminar pel\u00edcula: 2055: Lost connection to MySQL server at '127.0.0.1:3306', system error: 10038 Se intent\u00f3 realizar una operaci\u00f3n en un elemento que no es un socket", "severity": "ERROR", "timestamp": "2024-10-23T13:26:40Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al eliminar pel\u00edcula: 2055: Lost connection to MySQL server at '127.0.0.1:3306', system error: 10038 Se intent\u00f3 realizar una operaci\u00f3n en un elemento que no es un socket", "severity": "ERROR", "timestamp": "2024-10-23T13:26:40Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-23T16:06:33Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-23T16:06:33Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-23T16:06:33Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-23T16:16:55Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-23T16:16:55Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-23T16:16:55Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-23T16:17:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-23T16:17:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-23T16:17:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-23T16:17:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-23T16:17:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-23T16:17:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-23T16:17:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T09:46:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T09:46:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T09:46:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:14:51Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:14:51Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:14:51Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:36Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:36Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:36Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:41Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:41Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:41Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:41Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:41Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:41Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:41Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:19:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:20:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:20:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:20:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:20:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:20:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:20:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:20:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:20:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:20:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:20:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:20:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:20:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:20:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:20:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:20:08Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:25:13Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:25:13Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:25:13Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:28:13Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:28:13Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:28:13Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:33:49Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No funciona", "severity": "ERROR", "timestamp": "2024-10-24T10:33:49Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No funciona", "severity": "ERROR", "timestamp": "2024-10-24T10:33:49Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:33:57Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:33:57Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:33:57Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No funciona", "severity": "ERROR", "timestamp": "2024-10-24T10:33:57Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No funciona", "severity": "ERROR", "timestamp": "2024-10-24T10:33:57Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No funciona", "severity": "ERROR", "timestamp": "2024-10-24T10:33:57Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No funciona", "severity": "ERROR", "timestamp": "2024-10-24T10:33:57Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:36:41Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Ocurri\u00f3 un error al modificar la pel\u00edcula: Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:36:41Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Ocurri\u00f3 un error al modificar la pel\u00edcula: Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:36:41Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:36:55Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:36:55Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:36:55Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Ocurri\u00f3 un error al modificar la pel\u00edcula: Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:36:55Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Ocurri\u00f3 un error al modificar la pel\u00edcula: Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:36:55Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Ocurri\u00f3 un error al modificar la pel\u00edcula: Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:36:55Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Ocurri\u00f3 un error al modificar la pel\u00edcula: Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:36:55Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:42:10Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Ocurri\u00f3 un error al modificar la pel\u00edcula: Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:42:10Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Ocurri\u00f3 un error al modificar la pel\u00edcula: Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:42:10Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:42:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:42:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:42:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Ocurri\u00f3 un error al modificar la pel\u00edcula: Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:42:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Ocurri\u00f3 un error al modificar la pel\u00edcula: Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:42:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Ocurri\u00f3 un error al modificar la pel\u00edcula: Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:42:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Ocurri\u00f3 un error al modificar la pel\u00edcula: Error al actualizar pel\u00edcula: No se encontr\u00f3 la pel\u00edcula con Id 26", "severity": "ERROR", "timestamp": "2024-10-24T10:42:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1146 (42S02): Table 'proyecto_final.historial_usuarios' doesn't exist", "severity": "ERROR", "timestamp": "2024-10-24T11:10:23Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al registrar historial de usuario: 1146 (42S02): Table 'proyecto_final.historial_usuarios' doesn't exist", "severity": "ERROR", "timestamp": "2024-10-24T11:10:23Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al registrar historial de usuario: 1146 (42S02): Table 'proyecto_final.historial_usuarios' doesn't exist", "severity": "ERROR", "timestamp": "2024-10-24T11:10:23Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1146 (42S02): Table 'proyecto_final.historial_usuarios' doesn't exist", "severity": "ERROR", "timestamp": "2024-10-24T11:11:50Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al registrar historial de usuario: 1146 (42S02): Table 'proyecto_final.historial_usuarios' doesn't exist", "severity": "ERROR", "timestamp": "2024-10-24T11:11:50Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al registrar historial de usuario: 1146 (42S02): Table 'proyecto_final.historial_usuarios' doesn't exist", "severity": "ERROR", "timestamp": "2024-10-24T11:11:50Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1146 (42S02): Table 'proyecto_final.historial_usuarios' doesn't exist", "severity": "ERROR", "timestamp": "2024-10-24T11:12:12Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al registrar historial de usuario: 1146 (42S02): Table 'proyecto_final.historial_usuarios' doesn't exist", "severity": "ERROR", "timestamp": "2024-10-24T11:12:12Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al registrar historial de usuario: 1146 (42S02): Table 'proyecto_final.historial_usuarios' doesn't exist", "severity": "ERROR", "timestamp": "2024-10-24T11:12:12Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "set_user() missing 1 required positional argument: 'grupo'", "severity": "ERROR", "timestamp": "2024-10-24T11:21:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "set_user() missing 1 required positional argument: 'grupo'", "severity": "ERROR", "timestamp": "2024-10-24T11:22:09Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "set_user() missing 1 required positional argument: 'grupo'", "severity": "ERROR", "timestamp": "2024-10-24T11:22:09Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'AgregarUsuario' object has no attribute 'sesion'", "severity": "ERROR", "timestamp": "2024-10-24T11:31:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "set_user() missing 1 required positional argument: 'grupo'", "severity": "ERROR", "timestamp": "2024-10-24T13:53:55Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'btn_actualizarH'", "severity": "ERROR", "timestamp": "2024-10-24T14:03:24Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'IdPelicula' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-24T22:44:39Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar usuario: 1054 (42S22): Unknown column 'IdPelicula' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-24T22:44:39Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar usuario: 1054 (42S22): Unknown column 'IdPelicula' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-24T22:44:39Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'IdPelicula' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-24T22:46:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'IdPelicula' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-24T22:46:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'IdPelicula' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-24T22:46:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar usuario: 1054 (42S22): Unknown column 'IdPelicula' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-24T22:46:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar usuario: 1054 (42S22): Unknown column 'IdPelicula' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-24T22:46:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar usuario: 1054 (42S22): Unknown column 'IdPelicula' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-24T22:46:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al insertar usuario: 1054 (42S22): Unknown column 'IdPelicula' in 'field list'", "severity": "ERROR", "timestamp": "2024-10-24T22:46:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Not all parameters were used in the SQL statement", "severity": "ERROR", "timestamp": "2024-10-25T20:33:37Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al eliminar la funci\u00f3n: Not all parameters were used in the SQL statement", "severity": "ERROR", "timestamp": "2024-10-25T20:33:37Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al eliminar la funci\u00f3n: Not all parameters were used in the SQL statement", "severity": "ERROR", "timestamp": "2024-10-25T20:33:37Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'id' in 'where clause'", "severity": "ERROR", "timestamp": "2024-10-25T20:35:32Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al eliminar la funci\u00f3n: 1054 (42S22): Unknown column 'id' in 'where clause'", "severity": "ERROR", "timestamp": "2024-10-25T20:35:32Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al eliminar la funci\u00f3n: 1054 (42S22): Unknown column 'id' in 'where clause'", "severity": "ERROR", "timestamp": "2024-10-25T20:35:32Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'connection'", "severity": "ERROR", "timestamp": "2024-10-25T20:36:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "obtener_usuario() missing 1 required positional argument: 'nombre'", "severity": "ERROR", "timestamp": "2024-10-28T18:41:14Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'comboBox_cartelera'", "severity": "ERROR", "timestamp": "2024-10-28T20:47:26Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'comboBox_cartelera'", "severity": "ERROR", "timestamp": "2024-10-28T20:50:26Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "tuple indices must be integers or slices, not str", "severity": "ERROR", "timestamp": "2024-10-29T09:37:03Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "tuple indices must be integers or slices, not str", "severity": "ERROR", "timestamp": "2024-10-29T09:48:12Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "tuple indices must be integers or slices, not str", "severity": "ERROR", "timestamp": "2024-10-29T09:53:38Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "tuple indices must be integers or slices, not str", "severity": "ERROR", "timestamp": "2024-10-29T09:54:38Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "tuple indices must be integers or slices, not str", "severity": "ERROR", "timestamp": "2024-10-29T09:55:30Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "tuple indices must be integers or slices, not str", "severity": "ERROR", "timestamp": "2024-10-29T09:57:29Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'desconectar'", "severity": "ERROR", "timestamp": "2024-10-29T09:59:33Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'desconectar'", "severity": "ERROR", "timestamp": "2024-10-29T10:00:32Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "tuple indices must be integers or slices, not str", "severity": "ERROR", "timestamp": "2024-10-29T10:09:15Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "list indices must be integers or slices, not str", "severity": "ERROR", "timestamp": "2024-10-29T10:10:19Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "list indices must be integers or slices, not str", "severity": "ERROR", "timestamp": "2024-10-29T10:12:33Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "0", "severity": "ERROR", "timestamp": "2024-10-29T10:24:09Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "0", "severity": "ERROR", "timestamp": "2024-10-29T10:25:23Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "too many values to unpack (expected 3)", "severity": "ERROR", "timestamp": "2024-10-29T10:31:57Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "0", "severity": "ERROR", "timestamp": "2024-10-29T10:34:51Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "0", "severity": "ERROR", "timestamp": "2024-10-29T10:36:37Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Unread result found", "severity": "ERROR", "timestamp": "2024-10-29T10:41:44Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Unread result found", "severity": "ERROR", "timestamp": "2024-10-29T10:42:06Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'Database' object has no attribute 'obtener_funcion_del_dia'", "severity": "ERROR", "timestamp": "2024-10-30T10:24:03Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'mostrar_pelicula'", "severity": "ERROR", "timestamp": "2024-10-30T10:53:10Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'layout_peliculas'", "severity": "ERROR", "timestamp": "2024-10-30T10:54:35Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'mostrar_pelicula'", "severity": "ERROR", "timestamp": "2024-10-30T10:57:22Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'layout_peliculas'", "severity": "ERROR", "timestamp": "2024-10-30T10:58:55Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'carpeta_imagenes'", "severity": "ERROR", "timestamp": "2024-11-01T08:36:57Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`proyecto_final`.`ventaboletos`, CONSTRAINT `fk_venta_usuario` FOREIGN KEY (`IdUsuario`) REFERENCES `usuarios` (`IdUsuarios`) ON DELETE SET NULL ON UPDATE CASCADE)", "severity": "ERROR", "timestamp": "2024-11-01T11:00:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1146 (42S02): Table 'proyecto_final.ventas' doesn't exist", "severity": "ERROR", "timestamp": "2024-11-03T08:54:55Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "strptime() argument 1 must be str, not datetime.datetime", "severity": "ERROR", "timestamp": "2024-11-03T10:57:58Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'boton_filtrar_fecha'", "severity": "ERROR", "timestamp": "2024-11-03T11:05:53Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:29Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:29Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:29Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:50Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:50Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:50Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:50Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:50Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:50Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:50Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:50Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:50Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:50Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error durante la consulta: 1932 (42S02): Table 'proyecto_final.usuarios' doesn't exist in engine", "severity": "ERROR", "timestamp": "2024-11-06T10:57:50Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'fecha_filtro_fin_f'", "severity": "ERROR", "timestamp": "2024-11-06T11:17:09Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'mover_ventana'", "severity": "ERROR", "timestamp": "2024-11-06T11:24:22Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'fecha_filtro_fin_f'", "severity": "ERROR", "timestamp": "2024-11-06T11:26:24Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'fecha_filtro_fin_f'", "severity": "ERROR", "timestamp": "2024-11-06T11:26:38Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'fecha_filtro_fin_f'", "severity": "ERROR", "timestamp": "2024-11-06T11:27:49Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'fecha_filtro_fin_f'", "severity": "ERROR", "timestamp": "2024-11-06T11:33:38Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'mostrar_todas_las_funciones'", "severity": "ERROR", "timestamp": "2024-11-06T11:37:27Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'mostrar_todas_las_funciones'", "severity": "ERROR", "timestamp": "2024-11-06T11:39:38Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'mostrar_todas_las_funciones'", "severity": "ERROR", "timestamp": "2024-11-06T11:45:16Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'feche_filtro_fin_f'", "severity": "ERROR", "timestamp": "2024-11-06T11:50:58Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'feche_filtro_fin_f'", "severity": "ERROR", "timestamp": "2024-11-06T11:51:45Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'feche_filtro_fin_f'", "severity": "ERROR", "timestamp": "2024-11-06T12:03:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'filtro_fecha_activado'", "severity": "ERROR", "timestamp": "2024-11-06T12:08:31Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'feche_filtro_fin_f'", "severity": "ERROR", "timestamp": "2024-11-06T12:08:36Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'feche_filtro_fin_f'", "severity": "ERROR", "timestamp": "2024-11-06T12:08:36Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'filtro_fecha_activado'", "severity": "ERROR", "timestamp": "2024-11-06T12:09:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'filtro_fecha_activado'", "severity": "ERROR", "timestamp": "2024-11-06T12:10:52Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'filtro_fecha_activado'", "severity": "ERROR", "timestamp": "2024-11-06T12:12:42Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'feche_filtro_fin_f'", "severity": "ERROR", "timestamp": "2024-11-06T12:18:51Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'btn_informacion_pelicula'", "severity": "ERROR", "timestamp": "2024-11-11T11:41:19Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'btn_informacion_pelicula'", "severity": "ERROR", "timestamp": "2024-11-11T11:41:48Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'btn_informacion_pelicula'", "severity": "ERROR", "timestamp": "2024-11-11T11:42:46Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'btn_informacion_pelicula'", "severity": "ERROR", "timestamp": "2024-11-11T12:16:15Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)", "severity": "ERROR", "timestamp": "2024-11-12T20:16:03Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "warning(parent: Optional[QWidget], title: Optional[str], text: Optional[str], buttons: Union[QMessageBox.StandardButtons, QMessageBox.StandardButton] = QMessageBox.Ok, defaultButton: QMessageBox.StandardButton = QMessageBox.NoButton): argument 1 has unexpected type 'Database'", "severity": "ERROR", "timestamp": "2024-11-12T20:16:03Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "warning(parent: Optional[QWidget], title: Optional[str], text: Optional[str], buttons: Union[QMessageBox.StandardButtons, QMessageBox.StandardButton] = QMessageBox.Ok, defaultButton: QMessageBox.StandardButton = QMessageBox.NoButton): argument 1 has unexpected type 'Database'", "severity": "ERROR", "timestamp": "2024-11-12T20:16:03Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "2003: Can't connect to MySQL server on '127.0.0.1:3306' (10061 No se puede establecer una conexi\u00f3n ya que el equipo de destino deneg\u00f3 expresamente dicha conexi\u00f3n)", "severity": "ERROR", "timestamp": "2024-11-12T20:38:49Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "warning(parent: Optional[QWidget], title: Optional[str], text: Optional[str], buttons: Union[QMessageBox.StandardButtons, QMessageBox.StandardButton] = QMessageBox.Ok, defaultButton: QMessageBox.StandardButton = QMessageBox.NoButton): argument 1 has unexpected type 'Database'", "severity": "ERROR", "timestamp": "2024-11-12T20:38:49Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "warning(parent: Optional[QWidget], title: Optional[str], text: Optional[str], buttons: Union[QMessageBox.StandardButtons, QMessageBox.StandardButton] = QMessageBox.Ok, defaultButton: QMessageBox.StandardButton = QMessageBox.NoButton): argument 1 has unexpected type 'Database'", "severity": "ERROR", "timestamp": "2024-11-12T20:38:49Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:22:11Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:22:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:22:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:22:24Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:22:24Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:22:24Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:23:15Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:23:22Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:23:22Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:23:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:23:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:23:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:23:34Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:23:34Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:23:34Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:23:34Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:24:41Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:24:47Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:24:47Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:24:53Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:24:53Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:24:53Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:24:58Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:24:58Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:24:58Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:24:58Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'estadisticas_individual'", "severity": "ERROR", "timestamp": "2024-11-12T21:36:07Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'estadisticas_individual'", "severity": "ERROR", "timestamp": "2024-11-12T21:36:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'estadisticas_individual'", "severity": "ERROR", "timestamp": "2024-11-12T21:36:17Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'estadisticas_individual'", "severity": "ERROR", "timestamp": "2024-11-12T21:36:21Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'estadisticas_individual'", "severity": "ERROR", "timestamp": "2024-11-12T21:36:21Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "'MainWindow' object has no attribute 'estadisticas_individual'", "severity": "ERROR", "timestamp": "2024-11-12T21:36:21Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:39:10Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:39:15Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:39:15Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:39:20Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:39:20Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:39:20Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:39:25Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:39:25Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:39:25Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:39:25Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:43:33Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:43:41Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:43:41Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:43:50Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:43:50Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:43:50Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:43:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:43:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:43:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:43:56Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:44:16Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:44:16Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:44:16Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:44:16Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:44:16Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:44:36Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:44:36Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:44:36Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:44:36Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:44:36Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:44:36Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:44:48Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:44:48Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:44:48Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:44:48Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:44:48Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:44:48Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-12T21:44:48Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-13T10:13:48Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-13T10:13:54Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-13T10:13:54Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-13T10:14:01Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-13T10:14:01Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-13T10:14:01Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-13T10:14:09Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-13T10:14:09Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-13T10:14:09Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-13T10:14:09Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:44:18Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:44:23Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:44:23Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:44:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:44:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:44:28Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:44:34Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:44:34Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:44:34Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:44:34Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:48:30Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:48:30Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:48:30Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:48:30Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:48:30Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:48:35Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:48:35Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:48:35Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:48:35Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:48:35Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "maximum recursion depth exceeded while calling a Python object", "severity": "ERROR", "timestamp": "2024-11-15T09:48:35Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'v.CantidadBoletos' in 'field list'", "severity": "ERROR", "timestamp": "2024-11-20T10:38:36Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al calcular el porcentaje de asistencia: 1054 (42S22): Unknown column 'v.CantidadBoletos' in 'field list'", "severity": "ERROR", "timestamp": "2024-11-20T10:38:36Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al calcular el porcentaje de asistencia: 1054 (42S22): Unknown column 'v.CantidadBoletos' in 'field list'", "severity": "ERROR", "timestamp": "2024-11-20T10:38:36Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'v.CantidadBoletos' in 'field list'", "severity": "ERROR", "timestamp": "2024-11-20T10:38:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'v.CantidadBoletos' in 'field list'", "severity": "ERROR", "timestamp": "2024-11-20T10:38:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'v.CantidadBoletos' in 'field list'", "severity": "ERROR", "timestamp": "2024-11-20T10:38:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al calcular el porcentaje de asistencia: 1054 (42S22): Unknown column 'v.CantidadBoletos' in 'field list'", "severity": "ERROR", "timestamp": "2024-11-20T10:38:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al calcular el porcentaje de asistencia: 1054 (42S22): Unknown column 'v.CantidadBoletos' in 'field list'", "severity": "ERROR", "timestamp": "2024-11-20T10:38:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al calcular el porcentaje de asistencia: 1054 (42S22): Unknown column 'v.CantidadBoletos' in 'field list'", "severity": "ERROR", "timestamp": "2024-11-20T10:38:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al calcular el porcentaje de asistencia: 1054 (42S22): Unknown column 'v.CantidadBoletos' in 'field list'", "severity": "ERROR", "timestamp": "2024-11-20T10:38:43Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "1054 (42S22): Unknown column 'v.CantidadBoletos' in 'field list'", "severity": "ERROR", "timestamp": "2024-11-20T10:47:15Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al calcular el porcentaje de asistencia: 1054 (42S22): Unknown column 'v.CantidadBoletos' in 'field list'", "severity": "ERROR", "timestamp": "2024-11-20T10:47:15Z"}
{"name": "error.logger", "filename": "logger.py", "lineno": 33, "message": "Error al calcular el porcentaje de asistencia: 1054 (42S22): Unknown column 'v.CantidadBoletos' in 'field list'", "severity": "ERROR", "timestamp": "2024-11-20T10:47:15Z"}
